### ISSUE TITLE
Issue with addRouteFromFile method.

### ISSUE THREAD

**Issue by Schnoop** [ARCANEDEV/Support#1]
I've installed your LogViewer package but the routes not working. I drilled the problem down to your method "addRouteFromFile" in your support package. The second parameter $needle has a default value set to "Routes\\".

``` php
    private function addRouteFromFile(SplFileInfo $file, $needle = 'Routes\\')
    {
        if ($file->isFile() && pathinfo($file, PATHINFO_EXTENSION) === 'php') {
            $pos = strpos($file->getRealPath(), $needle);

            echo '<pre>' . print_r($file->getRealPath(), 1) . '</pre>';
            var_dump($pos);

            if ($pos !== false) {
                $route  = substr(
                    str_replace('.php', '', $file->getRealPath()),
                    $pos + strlen($needle)
                );
                $this->addRoute($route);
            }
        }
    }
```

I've printed out the real path of $file which is "/home/vagrant/Code/project/vendor/arcanedev/log-viewer/src/Http/Routes/LogViewerRoute.php" in my case. As you can see the $needle is not matching my path so the pos will be false and the routes will never be registered. Please have a look. My temporary fix is to remove the backslashes and increase $pos + 1.

**Comment by arcanedev-maroc** [comment]
@Schnoop Nice :+1:

**Comment by arcanedev-maroc** [comment]
Quick Fix: https://github.com/ARCANEDEV/Support/commit/e603730820cb6b8e51b02a4cb6661c18d8771b5d
