### ISSUE TITLE
request() helper doesn't match Laravel >= 5.3

### ISSUE THREAD

**Issue by sebdesign** [ARCANEDEV/Support#15]
- Support Version: 4.1.4
- Laravel Version: 5.4.15
- PHP Version: 5.6.29

### Description:

I'm using the arcanedev/log-viewer package, and for some reason composer loads `helpers.php` from this package **before** laravel's foundation helpers file. The `request()` helper here is not compatible with the one shipped after Laravel 5.3, and returns null when passing an array.

See: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L661

### Steps To Reproduce:

1. Install `arcanedev/log-viewer`

2. Add the following route:
```php
Route::get('test', function () {
    dump(request(['foo', 'bar']));
});
```

3. Go to `/test?foo=1&bar=2`

The response is `null` instead of `['foo' => 1, 'bar' => 2]` .

**Comment by arcanedev-maroc** [comment]
Can you update the support package and see if it's solved ?

**Comment by sebdesign** [comment]
Thanks! That was it. 🥇
