### ISSUE TITLE
Collection File missing?

### ISSUE THREAD

**Issue by ArditMustafaraj** [ARCANEDEV/Support#23]
Just made an upgrade of the package and got an error: Class Collection not found. 
I think the /src/Collection.php is not inlcuded in this release.

**"Class 'Arcanedev\Support\Collection' not found"**

**Comment by arcanedev-maroc** [comment]
Are you using `arcanedev/support` package directly ?

If Yes, downgrade the version to `"arcanedev/support": "4.2.*"`

The `Arcanedev\Support\Collection` was deprecated in `v4.3`

Check: https://github.com/ARCANEDEV/Support/blob/laravel-v5.5/src/Collection.php#L11

**Comment by ArditMustafaraj** [comment]
No I'm using it with **Log-Viewer** and the issue happened on `composer update`

**Comment by arcanedev-maroc** [comment]
I'm working on it: https://github.com/ARCANEDEV/LogViewer/pull/189

Laravel 5.6 FTW

**Comment by ArditMustafaraj** [comment]
Thanks. I appreciate your fast response.

**Comment by arcanedev-maroc** [comment]
The new version of LogViewer package was released 🎉 

Make sure you install the correct version for your laravel project: https://github.com/ARCANEDEV/LogViewer/blob/master/_docs/1.Installation-and-Setup.md#version-compatibility

**Comment by ArditMustafaraj** [comment]
Works great! Thanks again
