### ISSUE TITLE
constant.php keep getting delete in my system. 

### ISSUE THREAD

**Issue by bbashel1** [ARCANEDEV/Support#28]
- Support Version: 4.5.0
- Laravel Version: 5.8
- PHP Version: 7.3.9

### Description:

From my `project/vendor/arcandev/support folder`, `constant.php` is kept deleting itself in every 10-15 mins. I have to delete the vendor folder and re-run `composer install` to work.  is it a bug in your package or it is something in my end? Is there any solution that I can fix permanently this issue?

**Comment by arcanedev-maroc** [comment]
Never happened to me. 

This is not related to this package, i can't help you with this one
