### ISSUE TITLE
Collection::whereIn() signature doesn't match Laravel 5.3

### ISSUE THREAD

**Issue by jsiebach** [ARCANEDEV/Support#6]
The new `whereIn()` function in L5.3 has a new signature.  This is throwing an error:

``` php
public function whereIn($key, array $values, $strict = true)
{
    return $this->filter(function ($item) use ($key, $values, $strict) {
        return in_array(data_get($item, $key), $values, $strict);
    });
}
```

in L5.3 it has no declaration for `array` type:

`public function whereIn($key, $values, $strict = true)`

I'm getting:

`ErrorException in Collection.php line 0: Declaration of Arcanedev\Support\Collection::whereIn($key, array $values, $strict = true) should be compatible with Illuminate\Support\Collection::whereIn($key, $values, $strict = false)`

Removing `array` will be backwards compatible andalso  fix this problem

**Comment by arcanedev-maroc** [comment]
Ok, thanks for reporting this issue.

I'm going to make a PR to fix it.

PR: #7

**Comment by arcanedev-maroc** [comment]
Done, i've removed the `whereIn` method from this repo and leave it to the Illuminate's Collection to deal with it and to avoid any conflict with it.

Thanks again 👍
